language: ruby
script:
- make travis-build
cache: bundler
deploy:
  provider: s3
  access_key_id: AKIAJMSIZXPFP75OTHMQ
  secret_access_key:
    secure: kuCdneg3Z7/4gvLg6olFIuD0qsRskC237zDnyLT+90FNuGGAzMJ/nRFXbMz3hJSiUD62ljlEN3+e018b1iFKUJ6H7wI9grseJMxJ8u78JKUXNXh3wuEdqVp51XKq+ZsAx6hkDywPUkCCncJVXun9eX9cdpzD2FCnGGUd5xqyr3yg6ZS9CbQ67y0QIRrm7aoh+P4hCz+RZgMJMHW5D49IvP8vSwpBw0adYusDydRyrfVaN5VzBK9wGt5N7lCgbP+LMLfTfOZKTUVcnNt4f26hcPwdWTdDH0uJ6k5G2qPGY4jJivbcAjOIpisbSs+7MpcvSEL19EinCp673iHSDrKw2u6x7+3kikg/GRHYOIFBxfdW0QF//Zf8d/LA5gYxu+pxenGUkTGE0PHJS3Il+6LXiN0ukmF+HhPc0UZTTB22icq3ruQzFEL4WLEgNsC+9FJBcOWMm7zSroO93MuenH79q02QCgxgqS9HtyG7UDkSMlK8FLEpm8KF5VPZqDJRedX92wbm5JytGGOLR6ZIIYBNBkRdxRP2YoCT1aOzfF65RRAc+GlwGZijgu5fccrqvEsELb3AZKyU+B4hfuNiPxM92nOakIbrJXuK5Yuizfko9I+VnW2G392nFlhcfBWnCFJk3W2voGG3VaHud8d91B8ZfXXGchlKIlTPOwYcC/c5Xlw=
  bucket: lightster-hub-prod
  local-dir: _site
  upload-dir: _site
  skip_cleanup: true
  region: us-east-1
  on:
    repo: lightster/hub
    branch: master
