# Set this to your company or organization name
organization_name: Our Company Hub

mission_statement: >
  Providing a foundation for<br />
  a basic internal company hub

vision_statement: >
  A world where even the smallest organizations
  are efficient to navigate effectively

# Track the usage of your company hub with analytics
google_analytics: ""

# Set this to "" for sites hosted at root of subdomain
baseurl: "/our-company-hub"

social_cards:
- network: twitter
  username: lightster
- network: twitter
  username: macaroonIO
  inverted: true
- network: facebook
  username: lightster
- network: github
  username: lightster
- network: linkedin
  username: lightster
  personal: true

collections:
  core_values:
    output: false
  strategic_goals:
    output: false
  personal_resources:
    output: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE*
  - Makefile
