# Set this to your organization name
organization_name: ""

# Set this to your organization URL or leave blank to use your Hub home
organization_url: ""

# Set this to your brand for the header; can be HTML
organization_brand_header: ""

# Set this to your brand for the auth page; can be HTML
organization_brand_auth: ""

mission_statement: >
  Providing a foundation for<br />
  a basic internal organization hub

vision_statement: >
  A world where even the smallest organizations
  are efficient to navigate effectively

# Set this to "" for sites hosted at root of subdomain
baseurl: "/hub"

social-cards:
- network: twitter
  username: lightster
- network: twitter
  username: macaroonIO
  inverted: true
- network: facebook
  username: lightster
- network: github
  username: lightster
- network: linkedin
  username: lightster
  personal: true

# Track the usage of your hub with analytics
google_analytics: "UA-96539558-1"

# Your Google maps API key
google_maps: "AIzaSyDufBzDi-Hg1O0ELSijlFmo4oG90fZg5fQ"



####
# Nothing below needs to be updated, unless you are doing something advanced!
#

permalink: /:title/

collections:
  core-values:
    output: false
  strategic-goals:
    output: false
  upcoming-events:
    output: true
  personal-resources:
    output: true
  work-resources:
    output: true
  auth:
    output: true
    permalink: /auth/:title.html

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE*
  - Makefile
  - vendor
